baseURL: 'https://driftlux.github.io'
title: Driftlux Blog
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: '探索技术与思想的漂流之旅'
homepage: 'https://driftlux.github.io'
defaultContentLanguage: 'zh'
googleAnalytics: ''
pagination:
  pagerSize: 10
hasCJKLanguage: true
copyright: "2026 Driftlux All rights reserved"
Author:
  name: "Driftlux"
  email: ""
menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: Archive
      url: /archives
      weight: 3
    - name: Guest
      url: /guestbook
      weight: 4
params:
  brand: HOME
  avatarURL: /images/avatar.png
  author: Driftlux
  authorDescription: 探索者 | 技术爱好者 | 终身学习者
  info: 在代码与文字之间漂流，记录技术探索与思考的旅程
  favicon: /images/avatar.png
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: data-dark-mode
  comments:
    giscus:
      enable: false
      repo: Driftlux/driftlux.github.io
      repo_id: ''
      category: Announcements
      category_id: ''
      mapping: pathname
      position: top
      lang: zh-CN
    utteranc:
      enable: false
      repo: Driftlux/driftlux.github.io
      issueTerm: pathname
  analytics:
    google:
      SiteVerificationTag: ''
    umami:
      enable: false
      website_id: ''
      url: ''
  guestbook:
    title: Guestbook
    description: Leave a comment below. It could be anything – question, appreciation, information, or even humor.
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/Driftlux'
languages:
  en:
    languageName: EN
  zh:
    languageName: 中
    author: Driftlux
    authorDescription: 探索者 | 技术爱好者 | 终身学习者
    info: 在代码与文字之间漂流，记录技术探索与思考的旅程
    guestbook:
      title: 留言板
      description: 您的评论，会让该网站更精彩！
    menu:
      main:
        - name: 文章
          url: /blog
          weight: 1
        - name: 标签
          url: /tags
          weight: 2
        - name: 历史
          url: /archives
          weight: 3
        - name: 留言板
          url: /guestbook
          weight: 4
taxonomies:
  series: series
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreLogs:
  - warning-goldmark-raw-html
